#!/usr/bin/env python3
import json
import sys

try:
    with open(r'd:\final\files (2)\main.ipynb', 'r', encoding='utf-8') as f:
        nb = json.load(f)
    
    # Fix all Unicode and layout issues
    fixed_count = 0
    
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and isinstance(cell['source'], list):
            # Join to check content
            full_text = ''.join(cell['source'])
            
            # Check  if this is the emailer cell with the duplicate
            if 'pdf.multi_cell(0, 5, f"  [{svc}]  {act}")' in full_text:
                # Rebuild source lines for this cel
                new_source = []
                skip_next = False
                for i, line in enumerate(cell['source']):
                    if skip_next:
                        skip_next = False
                        continue
                    
                    # Replace the problematic multi_cell lines
                    if 'pdf.multi_cell(0, 5, f"  [{svc}]  {act}")' in line:
                        new_source.extend([
                            '            # Sanitize text: remove special chars\n',
                            '            svc_clean = "".join(c for c in svc if c.isascii() and (c.isalnum() or c in " -"))\n',
                            '            act_clean = "".join(c for c in act if c.isascii())\n',
                            '            text = f"  [{svc_clean}] {act_clean[:80]}"\n',
                            '            # Use cell instead of multi_cell\n',
                            '            if pdf.get_y() > 250:\n',
                            '                pdf.add_page()\n',
                            '            pdf.cell(0, 5, text, ln=True)\n',
                        ])
                        fixed_count += 1
                    elif 'pdf.multi_cell(0, 4,' in line and i > 0 and 'pdf.ln(4)' in cell['source'][i-1]:
                        # Fix the disclaimer multi_cell
                        new_source.extend([
                            '    disclaimer = ("DISCLAIMER: This report was auto-generated by NetGuard. "\n',
                            '                  "All scans target authorised test/lab environments only. "\n',
                            '                  f"Generated: {scan_time}.")\n',
                            '    disclaimer_clean = "".join(c for c in disclaimer if c.isascii())\n',
                            '    pdf.cell(0, 4, disclaimer_clean[:100], ln=True)\n',
                        ])
                        # Skip the next few lines which are the old multi_cell content
                        j = i + 1
                        while j < len(cell['source']) and 'f"Generated' not in cell['source'][j]:
                            j += 1
                        # Set index for next iteration to skip these lines
                        for _ in range(j - i):
                            if i + 1 < len(cell['source']):
                                cell['source'].pop(i + 1)
                        fixed_count += 1
                    else:
                        new_source.append(line)
                
                cell['source'] = new_source
    
    with open(r'd:\final\files (2)\main.ipynb', 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    
    print(f'✅ Successfully fixed {fixed_count} issues')
    print('✅ Notebook permanently fixed and saved')
    
except Exception as e:
    print(f'ERROR: {e}')
    import traceback
    traceback.print_exc()
    sys.exit(1)
